### ISSUE TITLE
Pushing to remote failed

### ISSUE THREAD

**Issue by ddieppa** [zaggino/brackets-git#1012]
[I'm supposed to describe steps to replicate my issue here and if I don't do that, I understand that my issue will be probably ignored.]

--------------------------------

*Brackets 1.3.0-16022 (win), Git 1.9.5.msysgit.1 & Brackets-Git 0.14.24*

**Pushing to remote failed**

```
Error: cmd-spawn-timeout: C:\Program Files (x86)\Git\cmd\git.exe push --porcelain --progress origin master
```

```
call: git push --porcelain --progress origin master
Error: cmd-spawn-timeout: C:\Program Files (x86)\Git\cmd\git.exe push --porcelain --progress origin master
    at timeoutPromise (file:///C:/Users/dadi/AppData/Roaming/Brackets/extensions/user/zaggino.brackets-git/src/Cli.js:219:27)
    at file:///C:/Users/dadi/AppData/Roaming/Brackets/extensions/user/zaggino.brackets-git/src/Cli.js:262:33
```

**Comment by ddieppa** [comment]
just trying to do a default git push

**Comment by zaggino** [comment]
Please read https://github.com/zaggino/brackets-git#features-and-limitations
