### ISSUE TITLE
Repo dropdown next to folder name?

### ISSUE THREAD

**Issue by mfromin** [zaggino/brackets-git#1014]
In some themes I see a select list / dropdown next to the folder name and in others I do not.  I tweaked a theme and really don't want to change to a new theme - how do I get this dropdown to show up for my selected theme.
![repo dropdown present](https://cloud.githubusercontent.com/assets/2193139/7372260/0767f238-ed83-11e4-8b97-d768b97f2194.png)
![repo dropdown not present](https://cloud.githubusercontent.com/assets/2193139/7372261/08811dfc-ed83-11e4-9742-4763cf98beea.png)

**Comment by zaggino** [comment]
it's a html element with id `git-branch-dropdown-toggle`, you should be able to show/hide it using css like any other ... our styles are here: https://github.com/zaggino/brackets-git/tree/master/styles - you just need to properly override them in the theme

**Comment by mfromin** [comment]
Apologies for being confused…

I don’t see any reference to that ID in the CSS for a theme that does show the toggle.  Where is this made visible in the theme?

--Michael

**Comment by zaggino** [comment]
the element should always be there if you're in a git repository:
```
$gitBranchName.parent().toggle(isRepositoryRootOrChild);
```
and is created by this piece of code on startup:
```
$("<div id='git-branch-dropdown-toggle' class='btn-alt-quiet'></div>")
            .append("[ ")
            .append($gitBranchName)
            .append(" ]")
            .on("click", function () {
                $gitBranchName.click();
                return false;
            })
            .appendTo("#project-files-header");
```

**Comment by mfromin** [comment]
So it turns out that Themes For Brackets has CSS that made the Folder button take over the entire area:

#project-files-header .btn-alt-quiet {
    Folder button border-radius: 0;
    width: 100%;
    margin: 0;
    background-color: #393939;
    padding: 10px;
}

Commenting out the width portion leads to now seeing the Git selection option.

--Michael

**Comment by zaggino** [comment]
:+1: ok, so that should be an easy fix, closing
