### ISSUE TITLE
Addon stop and gives no response

### ISSUE THREAD

**Issue by berong91** [zaggino/brackets-git#1021]
I have a SSH Authentication setup in my github account with a SSH key in my git config.

Trying to make a pull and push request from a GitHub repository doesn't show any reponses;
Also, I have to kill process git.exe and ssh.exe in task manager after I close Intel XDK.

[I'm supposed to describe steps to replicate my issue here and if I don't do that, I understand that my issue will be probably ignored.]

--------------------------------

*Brackets 1.1.0-0 (win), Git 1.9.5.msysgit.1 & Brackets-Git 0.14.17*

```
#1. ExpectedError: Nothing is selected!
```

**Comment by zaggino** [comment]
Extension doesn't work well with SSH, it's a known problem: https://github.com/zaggino/brackets-git#features-and-limitations

**Comment by berong91** [comment]
Omg I'm sorry about that, I should have read the README first. Thank you.
