### ISSUE TITLE
Shortcut "Collapse all" overrides Mac OSX logical (||) on spanish keyboards

### ISSUE THREAD

**Issue by PhysicsApp** [zaggino/brackets-git#1028]
Shortcut "Collapse all" overrides Mac OSX logical (||) on spanish keyboards
I didn't found a way to change this behavior

**Comment by zaggino** [comment]
What's "Collapse all" ? You probably wanted to open an issue with https://github.com/adobe/brackets and not with `brackets-git` extension.
