### ISSUE TITLE
changing branches triggers "gulp watch"

### ISSUE THREAD

**Issue by codeofsumit** [zaggino/brackets-git#1034]
I'm using gulp as a build tool. `gulp watch` watches for file changes. When changing branches, the watcher is triggered and creates "new" min-files although the min-files should be exactly the same as in the branch i changed to. I always `discard changes` but it's annoying nonetheless.

Any idea what could cause this?

**Comment by zaggino** [comment]
Can you post a snippet of your watch task?

**Comment by codeofsumit** [comment]
of course:
```
// Watch
gulp.task('watch', function() {

  // Watch .scss files
  gulp.watch('src/css/**/*.scss', ['styles']);

  // Watch .js files
  gulp.watch('src/js/**/*.js', ['scripts']);

});


// Styles
gulp.task('styles', function() {
  return gulp.src('src/css/app.scss')
    .pipe(sass({ 
        style: 'expanded',
        "sourcemap=none": true,
        noCache: true 
    }))
    .pipe(autoprefixer('last 2 version', 'safari 5', 'ie 8', 'ie 9', 'opera 12.1', 'ios 6', 'android 4'))
//    .pipe(gulp.dest('dist/styles'))
    .pipe(rename({ suffix: '.min' }))
    .pipe(minifycss())
    .pipe(gulp.dest('dist/css'))
    .pipe(notify({ message: 'Styles task complete' }));
});

// Scripts
gulp.task('scripts', function() {
  return gulp.src([
      'src/js/config.js',
      'src/js/helper.js',
      'src/js/app.js',
      'src/js/page.js',
	  'src/js/views/page.js',
      'src/js/**/*.js'
  ])
    .pipe(jshint('.jshintrc'))
    .pipe(jshint.reporter('default'))
    .pipe(concat('app.js'))
//    .pipe(gulp.dest('dist/scripts'))
    .pipe(rename({ suffix: '.min' }))
    .pipe(uglify())
    .pipe(gulp.dest('dist/js'))
    .pipe(notify({ message: 'Scripts task complete' }));
});
```

**Comment by zaggino** [comment]
[watch](https://www.npmjs.com/package/gulp-watch) is better for this sort of thing than default `gulp.watch`, this is how my gulp is set up:
```
var watch = require('gulp-watch');
gulp.task('watch', function () {
  watch('src/js/**/*.js', function (file) {
    var filePath = path.relative(__dirname, file.path);
    console.log(filePath);
  });
});
```
you'll see, which files get picked up by watch in the console and then we should be able to find out more about the issue

**Comment by zaggino** [comment]
See for example here: https://github.com/zaggino/brackets-npm-registry/blob/master/gulpfile.js#L90-L98

**Comment by zaggino** [comment]
to replace your:
```
gulp.watch('src/css/**/*.scss', ['styles']);
```
i'd personally do:
```
var watch = require('gulp-watch');
var runSequence = require('run-sequence');
watch('src/css/**/*.scss', function (file) {
  var filePath = path.relative(__dirname, file.path);
  console.log(filePath);
  runSequence('styles');
});
```

**Comment by codeofsumit** [comment]
So you think it's a `gulp.watch` problem? I was under the impression that brackets-git may make some changes to the files when changing branches. I haven't had this problem with earlier versions of brackets-git.

**Comment by codeofsumit** [comment]
ouu never mind I'm terribly sorry. It works like a charm now after updateing brackets and brackets-git again. I apparently overlooked some updated.
