### ISSUE TITLE
Pushing to remote failed

### ISSUE THREAD

**Issue by ignaciohita** [zaggino/brackets-git#1043]
Hello,

I am having problems with this extension when I want to push to remote server (commit is working).
My GIT server is requiring authentication with a SSH key, I have followed the instructions in "Working with SSH repositories" and I have checked that is working with SourceTree, there is a section to set my ppk and it is working. With brackets-git I'm getting this error even when I have Putty managing the private keys with the SSH agent present in the task bar.

Thanks a lot!

--------------------------------

*Brackets 1.3.0-16022 (win), Git 1.9.5.msysgit.0 & Brackets-Git 0.14.27*

**Pushing to remote failed**

```
Error: cmd-spawn-timeout: git push --porcelain --progress origin master
```

```
call: git push --porcelain --progress origin master
Error: cmd-spawn-timeout: git push --porcelain --progress origin master
    at timeoutPromise (file:///C:/Users/j.hita/AppData/Roaming/Brackets/extensions/user/zaggino.brackets-git/src/Cli.js:219:27)
    at file:///C:/Users/j.hita/AppData/Roaming/Brackets/extensions/user/zaggino.brackets-git/src/Cli.js:262:33
```

**Comment by zaggino** [comment]
if you execute the command in the error manually, does it complete without your interaction? how long does it take?

**Comment by ignaciohita** [comment]
Thanks for quick reply.

Good one, if I execute the command in the command line directly it is prompting me for the password of the key. I think that's why brackets-git is timing out.

Is there any way to specify key password in any place to avoid this?

Thanks!

**Comment by zaggino** [comment]
No, you need to set-up a ssh key for your machine without the password protection or just use https with brackets-git. It's a known problem and there's no easy way to fix it right now.

**Comment by ignaciohita** [comment]
Do you know a quick way to do that?

Thanks!

**Comment by ignaciohita** [comment]
I did it with with PuTTYgen exporting id_rsa and id_rsa.pub withoud password.

Thanks mate, it's amazing the support you are giving to this extension, you helped me to solve this is less than 3 hours!! Congrats :)

**Comment by zaggino** [comment]
:+1: Thx, hopefully this will be fully fixable in the 1.x version
