### ISSUE TITLE
ExpectedError: Folder /opt/brackets/samples/root/Getting Started/ is not writable!

### ISSUE THREAD

**Issue by sanderjo** [zaggino/brackets-git#1048]
I just installed brackets (Release 1.3 experimental build 1.3.0-16022 (release cd0a6aae5) ) and brackets-git (0.14.27) on my Ubuntu 15.04.

When I click on Init, I get a popup saying:
```
Brackets Git encountered an error
Initializing new repository failed
ExpectedError: Folder /opt/brackets/samples/root/Getting Started/ is not writable!
```
I can't find where to change that setting. It will probably turn out to be something simple. As I couldn't find this error message via Google, I'm reporting it here.

Strangely enough, the brackets stdout/stderr shows Pipelight / Silverlight messages 

I'll check on another Ubuntu what happens.

UPDATE: on my other Ubuntu, I get the same error message.

Command line shows:
```
$ brackets 
ATTENTION: default value of option force_s3tc_enable overridden by environment.
[0524/205556:ERROR:sandbox_linux.cc(130)] InitializeSandbox() called with multiple threads in process gpu-process
[0524/205611:ERROR:sandbox_linux.cc(130)] InitializeSandbox() called with multiple threads in process utility
```

*Brackets 1.3.0-16022 (linux), Git 2.1.4 & Brackets-Git 0.14.27*

**Comment by sanderjo** [comment]
Something simple indeed: start Brackets, then select Open Folder, and choose the (writable) folder.

... and then it works! :-)

**Comment by TElphee01** [comment]
You should really specify that this writable folder selection will actually be the actual local path of the repository.
