### ISSUE TITLE
Brackets GIT : Error Failed to connect to NodeJS

### ISSUE THREAD

**Issue by vishnurs** [zaggino/brackets-git#1058]
There is a problem with brackets, I couldn't install any extensions. So I have copied the GIT Brackets to the extensions folder. All other extensions are working except Brackets GIT. When I open Brackets, I am getting this error 

**Failed to Connect to Node JS. If you've just updated the extension then close all instances of brackets and try starting again. If restart doesn't help try removing other extensions that you've installed as one of them is probably causing the problem
ExpectedError: Error: Max connection attempts reached
**

When I check the console I am getting this errors

**WebSocket connection to 'ws://localhost:49308/' failed: Error in connection establishment: net::ERR_TUNNEL_CONNECTION_FAILED**

**Unknown installation error extensionManager domain is undefined**

I have checked lot of solutions online, in one it was mentioned to add `127.0.0.1` as `localhost` in `host file`. Even I did it, stil couldn't figure out what is causing the issue. I am working in `Windows 7` environment.

Please help. Thanks.

**Comment by zaggino** [comment]
This is fixed in https://github.com/zaggino/brackets-electron/releases
