### ISSUE TITLE
.DS_STORE is always committed

### ISSUE THREAD

**Issue by Sherlock92** [zaggino/brackets-git#1059]
On osx, .DS_STORE is committed every time, the only way to prevent this is by including it in .gitignore. 

Steps to reproduce:

- Create .DS_STORE file in local repo folder
- Open brackets-git in brackets, note that the file does not appear as a new file.
- Make a change to another source file, this file appears now.
- Select all files to commit (there is just one file changed however).
- Commit and push. Note the .DS_STORE file has been pushed.

**Comment by FezVrasta** [comment]
It's the way git works, it's not a bug.

**Comment by T3charmy** [comment]
@Sherlock92 might not be a bad idea to do this if you haven't: http://stackoverflow.com/a/19299889
