### ISSUE TITLE
Refreshing gutter failed!

### ISSUE THREAD

**Issue by ckoo7** [zaggino/brackets-git#1122]
[I'm supposed to describe steps to replicate my issue here and if I don't do that, I understand that my issue will be probably ignored.]

--------------------------------

*Brackets 1.4.0-16380 (linux), Git 2.5.0 & Brackets-Git 0.14.28*

**Refreshing gutter failed!**

```
Error: cmd-spawn-timeout: git status -u --porcelain -- public/s/dist/scripts/app.bundle.min.js
```

```
call: git status -u --porcelain -- public/s/dist/scripts/app.bundle.min.js
Error: cmd-spawn-timeout: git status -u --porcelain -- public/s/dist/scripts/app.bundle.min.js
    at timeoutPromise (file:///home/chandra/.config/Brackets/extensions/user/zaggino.brackets-git/src/Cli.js:219:27)
    at file:///home/chandra/.config/Brackets/extensions/user/zaggino.brackets-git/src/Cli.js:273:29
```

**Comment by DigitalLeaves** [comment]
Why are these being closed? There are many of them so, obviously, brackets git is having some trouble. I am right now getting lots of these messages, every 1 minute.  It's really frustrating. Any idea on how to fix that you can share here before closing? Or any suggestion to help us give you more information about the issue?
