### ISSUE TITLE
dont work

### ISSUE THREAD

**Issue by yanivz** [zaggino/brackets-git#1124]
[I'm supposed to describe steps to replicate my issue here and if I don't do that, I understand that my issue will be probably ignored.]

--------------------------------

*Brackets 1.4.0-16380 (win), Git 1.9.5.msysgit.1 & Brackets-Git 0.14.28*

```
#1. Error: cmd-spawn-timeout: git push --porcelain --progress origin master
#2. Error: cmd-spawn-timeout: git push --porcelain --progress origin master
```

**Comment by Pysis868** [comment]
The preferences page does state that if you continue to have timeouts, you could enter in a Username and Password to see if that fixes your problem.
You might want to try the last suggestion (currently) posted by laubsterboy on Jul 30, 2015, at 10:18 AM EDT about setting "GIT_SSH".  I did that to eliminate the 'enter passphrase' prompt that was causing this timeout message to appear, along with having pageant running with the key.
If you still have the problem, the rest of that post may be helpful as well.
