### ISSUE TITLE
Extension does not load

### ISSUE THREAD

**Issue by spietrek** [zaggino/brackets-git#1145]
I am having an issue where the Brackets Git extension only load very infrequently. I didn't notice this issue prior to the last update. I turned on Debug; however, the extension is not loading so nothing is added to the Brackets console. Generally, it takes ~10-20 times restarting Brackets before it finally loads.

The other extensions I have loaded include:
1. AngularJS Code Hints
2. Brackets Beautify
3. Brackets Bower
4. Brackets Commands Quick Search
5. Brackets Css Color Preview
6. Brackets Dash
7. Brackets Git
8. Brackets Icons
9. Ceratrior II theme
10. Duplicate Files & Folders
11. Extensions Rating
12. File Tree Exclude
13. HTML Block Selector
14. Indent Guides
15. Interactive Linter
16. Markdown Preview
17. Minifier
18. Minimap
19. Paste & Indent
20. Select Lines
21. Tabs - Custom Working
22. Whitespace Normalizer

What should I look out for to determine why the extension is not loading?

Thanks

-Steve

**Comment by zaggino** [comment]
Hi Steve, to start, disable/uninstall all extensions except Brackets Git and see if the problem persists, if it doesn't then try enabling extensions one by one to see which one is causing a problem. If it does persist even with all disabled, try deleting `state.json` typically in `C:\Users\<username>\AppData\Roaming\Brackets`

**Comment by spietrek** [comment]
Thanks. I will try it out.

-Steve Pietrek

**Comment by spietrek** [comment]
I removed the following extensions and have not had another occurrence of the extension not loading.

1. Brackets Dash
2. HTML Block Selector
3. Markdown Preview
4. Minifier
5. Select Lines

Not sure which one caused the error, assuming it is fixed, but I'm leaning toward Minifier since the other extensions were installed for a few months and the issue just started occurring within the past few weeks (during this time I installed Minifier).

Thanks

**Comment by zaggino** [comment]
Ah, yes - this has happened before:
https://github.com/zaggino/brackets-git/issues/911#issuecomment-74401480
https://github.com/zaggino/brackets-git/issues/766#issuecomment-60834785

**Comment by zaggino** [comment]
And also see https://github.com/wylst/brackets-minifier/issues/23 :)

**Comment by spietrek** [comment]
Ha! Interesting. Glad things are working now. Really enjoy using your extension! 

-Steve Pietrek
