### ISSUE TITLE
.gitignore is not respected for a file

### ISSUE THREAD

**Issue by entepe85** [zaggino/brackets-git#1147]
Upon setting up a git commit a JavaScript file which is generated through a gulp task gets committed even though it is explicitly ignored through .gitignore. Moreover both the script concatenation and compression task and the scss compilation task are triggered through gulp watch upon committing the corresponding files.

--------------------------------

*Brackets 1.4.0-16380 (mac), Git 2.3.2 (Apple Git-55) & Brackets-Git 0.14.29*

**Comment by zaggino** [comment]
1) What do you mean by `.gitignore` not being respected, in brackets ui or when you're going to commit?
2) Turn off `clean whitespace on commit` feature to stop your watch task being triggered.

**Comment by entepe85** [comment]
Sorry for not being clear enough on 1), I intended to point out that when I'm making a commit the file is not ignored (as it should) but rather proposed for the commit in the commit ui.

Thanks for the hint to turn off the whitespace cleaning.

**Comment by entepe85** [comment]
Alright, it looks like it was just me being stupid and having the file in the index even though it was explicitly ignored. So it was a general git issue and doesn't have to do with this extension.
