### ISSUE TITLE
.git folder appears in file explorer, then `Max connection attempts reached when connecting to NodeJS` popup

### ISSUE THREAD

**Issue by Owumaro** [zaggino/brackets-git#1149]
I just updated to Brackets 1.4.0-16380 (release 273804eb3) on Ubuntu 14.04.
I'm having the issue :

```
Failed to connect to NodeJS. If you just updated the extension close all instances of Brackets and try starting again.

Error: Max connection attempts reached
```

The strange thing is that it only affects one of my projects (a coffeescript/js project). My other projects (html/ruby) still work perfectly.

When I open the project, everything seems to work. After a few seconds the `.git` folder appears in the file explorer, and then if I click on `master` to switch branch, the popup appears with `Failed to connected to NodeJS[...]`. Then the branch dropdown menu doesn't work even if I click again.

I've read many related issues (#410 and friends), tryed to disable all the others extensions but it didn't work.

**Comment by zaggino** [comment]
Is it a large project ? Have you tried using `File Tree Exclude` extension from Jon Wolfe (it excludes node_modules from brackets) ?

**Comment by antoinematyja** [comment]
You were right ! I had a huge mongodb data file in my repository, and it seems like Brackets doesn't like it anymore (its size hasn't changed before/after updating to Brackets 1.4 but now it breaks everything...). I moved it somewhere else and now everything works fine.

So I guess this is a brackets issue. Maybe brackets-git could handle the related error more properly.

Many thanks zaggino !

**Comment by Owumaro** [comment]
You were right ! I had a huge mongodb data file in my repository, and it seems like Brackets doesn't like it anymore (its size hasn't changed before/after updating to Brackets 1.4 but now it breaks everything...). I moved it somewhere else and now everything works fine.

So I guess this is a brackets issue. Maybe brackets-git could handle the related error more properly.

Many thanks zaggino !

**Comment by zaggino** [comment]
What was the extension of the file? It was a data file? How big please?

Brackets-Git can't really do much about this, it's a failure of Brackets' internal stuff. If Brackets-Git failed to load, many other things like probably doesn't work too (installing extensions, live preview, ...)

**Comment by Owumaro** [comment]
It was mongodb data so it was BSON files. The files extensions are `.0`, `.1` etc... and `.ns`. But now I have a smaller database (with `.0` and `.ns` files) and it works so the issue is just the size of the files.

I understand that you can't deal with it from an extension, but I thought that maybe Brackets throws an Exception to the extensions when it fails itself.

**Comment by zaggino** [comment]
Thanks @Owumaro , I've taken this to upstream, see related bug above.
