### ISSUE TITLE
Default Terminal Command is wrong for Git-for-Windows 2.5

### ISSUE THREAD

**Issue by Hirse** [zaggino/brackets-git#1152]
After installing the latest version of Git-for-Windows, the open Terminal Button doesn't work anymore.

I am now using the 64bit version of Git, but the default path still points to a 32bit directory.
 
I am assuming the right path would be `C:\Program Files\Git\git-bash.exe` or something similar but that just opens the terminal for an instant.

**Comment by Hirse** [comment]
Found the solution in the registry for the context menu entry:
The command should be `C:\Program Files\Git\git-bash.exe` and the argument needs to be adapted as well to `--cd=$1`
![2015-08-21 10-20-18](https://cloud.githubusercontent.com/assets/2564094/9404282/7f2d48d4-47ee-11e5-806a-6cf6b5b2ce16.png)

**Comment by zaggino** [comment]
Hi @Hirse , by default it points to the `Git Bash.vbs` script in Git installation folder.

**Comment by Hirse** [comment]
Yes, but my new Git installation (git version 2.5.0.windows.1) doesn't seem to have that script.

**Comment by zaggino** [comment]
I'll have to test this one to see what the setting/default should be, haven't installed it yet.

**Comment by zaggino** [comment]
@Hirse this config works for me:
![image](https://cloud.githubusercontent.com/assets/1067319/9410890/33ddc480-4866-11e5-8f29-618d748766df.png)

**Comment by zaggino** [comment]
I'll make some kind of autodetect for this then in the next version.

**Comment by Hirse** [comment]
Without the argument the window closed instantly here. 
(I installed Git using the MINGW option btw)

**Comment by zaggino** [comment]
You're right, thanks for the solution, saved me a bit of time :) Published new version.

**Comment by Hirse** [comment]
Did you release it to the Extension Registry yet?

**Comment by zaggino** [comment]
Just to npm registry, the brackets one was telling me invalid zip file once again...
