### ISSUE TITLE
Using git-ftp

### ISSUE THREAD

**Issue by eridanired** [zaggino/brackets-git#1154]
Hello.

Fresh installation of git, brackets, brackets-git and git-ftp.

After enabling git-ftp can create new "Git-FTP remotes" via the dropdown menu. But when trying to upload stuff or even deleting the previously created "remote entry" the 1st error pops.

Then I noticed that git on OSX Yosemite installs (by default) to `/usr/local/git/bin/` instead of `/usr/local/bin/` which was the path used in earlier OSX versions. Also if git is installed via Homebrew instead of the oficial installer (from git-scm.com) it installs to `/usr/local/Cellar/git/ver.sion.num.ber/bin/`.

In any case; dropping the `git-ftp` script on any of those `/bin/` directories gave the same result: error # 1 listed below.

But moving the script to `/usr/local/Cellar/git/2.5.0/libexec/git-core/` or to the corresponding `/libexec/git-core/` directory of the current installation, error  # 1 is sorted out.

So it finally found the script!, but then got the second error listed below. Seems to be a permission problem. 

These are the permissions shown by `ls -l` on that specific file `-rw-rw-rw-@   1 eridani  admin   397394 Aug 23 12:58 git-ftp`.

Any thoughts?

--------------------------------

*Brackets 1.4.0-16380 (mac), Git 2.5.0 & Brackets-Git 0.14.32*

```
#1. Error: git: 'ftp' is not a git command. See 'git --help'.

Did you mean this?
	fetch
#2. Error: fatal: cannot exec 'git-ftp': Permission denied
```

**Comment by zaggino** [comment]
Hi @eridanired , I don't use git-ftp much but first guess is probably that you'll need to do `chmod +x` on that script file.

**Comment by eridanired** [comment]
Hey @zaggino !
That did the trick, thank you very much.
