### ISSUE TITLE
show many <<<<<< 

### ISSUE THREAD

**Issue by julianhartadi** [zaggino/brackets-git#1161]
hi i am start using bracket gits today, in the beginning page show many <<<<<< in the beginning and end of my script file, thanks for you apreciation

--------------------------------

*Brackets 1.4.0-16380 (linux), Git 1.9.1 & Brackets-Git 0.14.32*

**Comment by zaggino** [comment]
https://www.google.com.au/search?q=git+merge+arrows

**Comment by julianhartadi** [comment]
ok, thanks
