### ISSUE TITLE
Pushing to remote failed

### ISSUE THREAD

**Issue by m0sk1t** [zaggino/brackets-git#1168]
[I'm supposed to describe steps to replicate my issue here and if I don't do that, I understand that my issue will be probably ignored.]

--------------------------------

*Brackets 1.4.0-16380 (linux), Git 1.9.1 & Brackets-Git 0.14.32*

**Pushing to remote failed**

```
Error: cmd-spawn-timeout: git push --porcelain --progress origin master
```

```
call: git push --porcelain --progress origin master
Error: cmd-spawn-timeout: git push --porcelain --progress origin master
    at timeoutPromise (file:///home/m0sk1t/.config/Brackets/extensions/user/zaggino.brackets-git/src/Cli.js:228:27)
    at file:///home/m0sk1t/.config/Brackets/extensions/user/zaggino.brackets-git/src/Cli.js:271:33
```

**Comment by matbeard** [comment]
Same issue here after updating to Brackets-Git 0.14.32

Any suggestions?

**Comment by zaggino** [comment]
This usually happens only when the git is waiting for the password.

**Comment by matbeard** [comment]
Not sure what's happening. I'm getting various errors when first attempting to push or pull, but 2 or 3 subsequent retries generally work.

**Comment by zaggino** [comment]
When it works, how long does it take?

**Comment by zaggino** [comment]
You may want to increase default git timeout from 30 seconds to 60?

![image](https://cloud.githubusercontent.com/assets/1067319/9633228/18cf6b04-51cf-11e5-847f-30cc437acb66.png)
