### ISSUE TITLE
Stop load status

### ISSUE THREAD

**Issue by bodninja** [zaggino/brackets-git#1175]
Hello, I use git to some Brackts have, I can not say why, but when I load the Brackets, it loads the Brackets git, does not accuse any mistakes.

I have some changes in my project to send my repository. but they are no longer being loaded on the panel to make the commit.

Already reinstalled Brackets, nodejs and bracketsgit. Nothing worked.

I ran some tests commands such as: "git status", it is informed that the files have not realized commit.

Can you help me?

--------------------------------

*Brackets 1.4.0-16380 (win), Git 2.5.2.windows.1 & Brackets-Git 0.14.32*

```
#1. Error: cmd-spawn-timeout: git status -u --porcelain
#2. Error: cmd-spawn-timeout: git status -u --porcelain
#3. Error: cmd-spawn-timeout: git status -u --porcelain
```

**Comment by zaggino** [comment]
`git status` is timing out (default timeout in settings dialog is 30 seconds) ... when you execute the command from the console, how long does it take?

**Comment by bodninja** [comment]
exactly, I have a high number of files. I changed the timeout to 300s (very high number) and loaded ...!

worked!

Thank you and sorry for the inconvenience by a simple mistake.

**Comment by zaggino** [comment]
No worries, closing.
