### ISSUE TITLE
Can't find git.exe

### ISSUE THREAD

**Issue by Kupla** [zaggino/brackets-git#1186]
It seem's like bracket-git can't find git.exe

```
ExpectedError: No Git has been found on this computer

Searched paths:
git
C:\Program Files (x86)\Git\cmd\git.exe
C:\Program Files\Git\cmd\git.exe
```

I've checked that there actually isn't path C:\Program Files\Git\ or C:\Program Files (x86)\Git\. GitHub is   installed at C:\Users\Sima\AppData\Local\GitHub\ and the folder looks like

![Folder](http://i.imgur.com/XzPlQ2E.png)

If image above doesn't show up: http://i.imgur.com/XzPlQ2E.png
That GitHub application is Application Reference (.appref-ms) and shell is powershell script.

**Comment by zaggino** [comment]
https://git-for-windows.github.io
