### ISSUE TITLE
Brackets-git stopped working after Xcode update

### ISSUE THREAD

**Issue by superwese** [zaggino/brackets-git#1191]
There may be different error messages as described in these issues:
#1180 #1181 #1184 
Mine was simply:
```
ExpectedError: No Git has been found on this computer
Searched paths:
git
/usr/local/git/bin/git
/usr/local/bin/git
/usr/bin/git

```

**Comment by superwese** [comment]
The solution is to invoke `git --version` on the console.
One will be prompted with
 ```Error: 
Agreeing to the Xcode/iOS license requires admin privileges, please re-run as root via sudo.
```
And `sudo git --version` will present you Apple's new license agreement, which may agree to.
If you do and restart Brackets git will be available.

**Comment by zaggino** [comment]
Thanks @superwese for the solution.
