### ISSUE TITLE
Install from extension manager

### ISSUE THREAD

**Issue by dmase44** [zaggino/brackets-git#1215]
When installing Brackets-git w/ the extension manager there was no listing file > Git Settings and no icon in the tool bar. When I open my local repo it has an icon for Github that takes me to my Github repo and a list to change branches in the task bar. No access to the git setting. Downloaded the zip archive and dropping it in the extension manager it installs with all the functionality. Am I the only one to have this issue?

**Comment by zaggino** [comment]
@dmase44 you probably installed a different git extension from the extension manager

**Comment by dmase44** [comment]
You are right. The other was Brackets Git Branch.
