### ISSUE TITLE
Code Folding Icons Not Showing

### ISSUE THREAD

**Issue by SYNTAG** [zaggino/brackets-git#1226]
I recently bought Windows 10 on a new computer and installed Brackets to it. I have this horrible issue where the code folding icons are not showing and are replaced by rectangles with an X inside of it (obviously means it can't load the character). I've tried just about everything on Windows 10 so I'm assuming it's Brackets that is doing this.

Here is an image of what I am seeing:
http://i.imgur.com/b2JRYMC.png

**Comment by zaggino** [comment]
This is not a git issue, submit it here: https://github.com/adobe/brackets
