### ISSUE TITLE
Refreshing gutter failed!

### ISSUE THREAD

**Issue by LeG3nDz** [zaggino/brackets-git#1235]
[I'm supposed to describe steps to replicate my issue here and if I don't do that, I understand that my issue will be probably ignored.]

--------------------------------

*Brackets 1.5.0-16538 (win), Git 2.5.1.windows.1 & Brackets-Git 0.14.32*

**Refreshing gutter failed!**

```
Error: cmd-spawn-timeout: git status -u --porcelain -- webroot/wp-content/themes/ice-dev/templates/loop-project.php
```

```
call: git status -u --porcelain -- webroot/wp-content/themes/ice-dev/templates/loop-project.php
Error: cmd-spawn-timeout: git status -u --porcelain -- webroot/wp-content/themes/ice-dev/templates/loop-project.php
    at timeoutPromise (file:///C:/Users/str/AppData/Roaming/Brackets/extensions/user/zaggino.brackets-git/src/Cli.js:228:27)
    at file:///C:/Users/str/AppData/Roaming/Brackets/extensions/user/zaggino.brackets-git/src/Cli.js:282:29
```

**Comment by DigitalLeaves** [comment]
Same problem here, only with JS files. Never happened to me before. Some things I consider may trigger the error:
- bad network connectivity
- lots of files in the project?

Any help regarding how to debug this issue is greatly appreciated. It's really frustrating and hampers my work productivity.

**Comment by zaggino** [comment]
@DigitalLeaves this extension (and probably whole Brackets editor) has been dead now for years. If you're interested about work productivity I'd suggest changing your editor to something more maintained like VS Code (that's what I did).

**Comment by DigitalLeaves** [comment]
Thanks! I can't agree about Brackets, but it's a shame you decided to stop developing the plugin. It was very good. Cheers!
