### ISSUE TITLE
Get Error while exit bash-console by closing the window

### ISSUE THREAD

**Issue by Lichtjaeger** [zaggino/brackets-git#1241]
If I use the button for opening a bash console in brackets-git and close the bash-window with ctrl+C or with other closing options I get an error. If I type 'exit' no error occures and the window closes normaly.

--------------------------------
*Brackets 1.5.0-16538 (win), Git 2.6.2.windows.1 & Brackets-Git 0.14.32*
```
#1. Error: Error: ^C: C:\Program Files\Git\git-bash.exe --cd="D:/Users/***/Documents/GitHub/wheelhouse/"
```

**Comment by zaggino** [comment]
Can't replicate on my windows, `ctrl+C` doesn't close the shell window for me.

**Comment by Lichtjaeger** [comment]
I've tried it out and you'r right. ctrl+c now only makes a new line (I have installed a new Version of git some day before and reseted the preferences). But I stil get the error if I close the bash-window other then by "exit"-command.

I have installed git with the option "Use git from Windows Command Prompt" and "Use Windows' default console window".

**Comment by Lichtjaeger** [comment]
I have a solution. My terminal command was set on git-bash.exe. I've downloaded the "Git Bash.vbs" and now use this.

It works!
