### ISSUE TITLE
Add a fetch button

### ISSUE THREAD

**Issue by mattbell87** [zaggino/brackets-git#1255]
There may be some cases when someone wants to fetch from their remote but not merge the changes. They might want to see how many commits they are behind or simply browse/diff the changes before merging them with the local copy. 

Here is a concept I created with the dev tools:
![screen shot 2016-01-12 at 8 47 22 am](https://cloud.githubusercontent.com/assets/2722612/12247670/246aeaa0-b909-11e5-86d6-700332517b8a.png)
**Edit:** removed second concept.

**Comment by zaggino** [comment]
Just make a sync button, fetch all remotes, without the dialog, that would be much simpler to use I guess.

**Comment by mattbell87** [comment]
One click sync, I like that idea. I'll develop that over the next couple of days.

**Comment by zaggino** [comment]
What about doing fetch automatically? Idea would be:

- Hook on `BRACKETS_PROJECT_CHANGE`
- Use Preferences to check if we fetched that project today
- If no, do fetch all remotes automatically and mark as fetched today

This would be great to have, I start Brackets in the morning, my remotes get fetched, counters get updated and I don't have to press fetch button manually. If the automatic fetch will fail, just log error in the console.

**Comment by mattbell87** [comment]
I thought about an automatic approach but concluded that it would be heavy on large projects. I still think an automatic fetch would be an awesome idea though.

I think we should implement the manual fetch button first, then look at creating a new feature for automatic fetches.

How about a drop down in the settings dialog?
![screen shot 2016-01-12 at 4 37 12 pm](https://cloud.githubusercontent.com/assets/2722612/12255703/cfb0f12a-b94a-11e5-9448-4cca8416b562.png)

**Comment by zaggino** [comment]
Yeah, that's a good idea too to have that dropdown.
