### ISSUE TITLE
Invalid commit counter number.

### ISSUE THREAD

**Issue by dnbard** [zaggino/brackets-git#1257]
Brackets Git v0.16.0 (started to reproduce after the update to v0.16.0)
Brackets 1.5

Invalid commit counter number. 

I have several remotes in my project (lets say 1 github + 1 custom hosted gitlab).
`origin` remote - github
`custom` remote - gitlab

I'm working in `custom` remote (not `origin`). My remote is ahead of `origin` by N commits.
Counter are showing the N number of non-pushed commits even if my working remote is `custom` and I've already pushed all these commits to it.

**Comment by mattbell87** [comment]
Must be something to do with the the rev-list command comparing upstream to head. I'll have to test this later.

**Comment by zaggino** [comment]
In the meanwhile, @dnbard can you post a result of:
```
git rev-list --left-right --count @{u}...@{0}
```
?

**Comment by zaggino** [comment]
@dnbard Can you install from master using url and check whether yours issue is fixed?

**Comment by dnbard** [comment]
@mattbell87  
`git rev-list --left-right --count @{u}...@{0}`
0       74

@zaggino yes, I can confirm that counter don't contain any unpushed commits with v0.16.1 (from the master branch)

**Comment by zaggino** [comment]
Released as `0.16.2`
