### ISSUE TITLE
Ammend last commit - not working

### ISSUE THREAD

**Issue by tabweg** [zaggino/brackets-git#1258]
"Ammend commit" stopped working.

When I hover the checkbox it says:
"Cannot amment commit when there are no unpushed commits"

I work locally and use FT Git to send file to FTP.
I don't use any remote Git repository for the project I'm working on.
So I don't push it anywhere.

It was working just fin before update today to latest version.

**Comment by zaggino** [comment]
I've just tested and it works fine with normal repositories.
Not sure about the FTP, I don't support that feature.

**Comment by tabweg** [comment]
It isn't relates to git-ftp itself.
It says that I can't amend a commit if I didn't pushed anything yet to a repository.

In version 0.15.0 it was working just fine (I switched back to it) and when I upgrade to version 0.16.0 I see this message that i can't amend the last commit.
And it is very annoying.

I have not set a remote repository and didn't pushed anything to it.
So it is like I just work locally using GIT for control version.

I don't have to explicitly set up some remote repository in general.

![brackets_2016-01-14_00-36-46](https://cloud.githubusercontent.com/assets/626593/12311361/f3f88c98-ba56-11e5-9bc0-639564f063d8.png)

**Comment by zaggino** [comment]
You can only ammend a commit, if you have an unpushed commit:
1) Make a local commit (don't push)
2) Make another commit - can amend
3) Push
4) Make another commit - can't amend because changing already pushed commit would require you to force push which is a bad practice.

I don't believe that this has changed in 0.16.
cc @mattbell87

**Comment by tabweg** [comment]
I created a simple test.
Git init, git commit and next commit can't be done.

Check the video:
https://drive.google.com/file/d/0B-iKSGe0ICTJNVdYbGlrZDlhNlU/view

**Comment by zaggino** [comment]
Thanks for the video, the bug is now fixed in master branch of the extension. Will be released shortly, if you wish to get it now, just install the extension from github link using `Install from URL...`

**Comment by tabweg** [comment]
Thank you.
