### ISSUE TITLE
Opening a Terminal sets the wrong node version

### ISSUE THREAD

**Issue by Hirse** [zaggino/brackets-git#1276]
When I use the Toolbar Button to open a Terminal (Git Bash on Windows) and try to use `node` the node version is not the one I have installed.

Instead it seems the node version that comes with Brackets is set as default.
Is that intentionally?
I would prefer to use my node version as it is more recent.

The top is opened from Brackets, the bottom is opened normally.
![brackets terminal](https://cloud.githubusercontent.com/assets/2564094/13197251/3b841eca-d7e8-11e5-8b60-a84bc6e091cb.png)

**Comment by zaggino** [comment]
Does this happen always? Might be a thing caused by `brackets-npm-registry`

**Comment by zaggino** [comment]
@Hirse please update `brackets-npm-registry` to `0.3.8` and try this again, hopefully it'll be fixed.

**Comment by Hirse** [comment]
Just updated and the issue seems to be still there.

**Comment by zaggino** [comment]
Another update of `brackets-npm-registry` to `0.4.0`. I can no longer replicate the problem in any way. If the problem still persists with your machine, can you try removing `brackets-npm-registry` from the extensions?

**Comment by Hirse** [comment]
I had some trouble to update, but after reinstalling `brackets-npm-registry` from GitHub the issue seems fixed.
