### ISSUE TITLE
Not working with Brackets 1.7

### ISSUE THREAD

**Issue by oskarnrk** [zaggino/brackets-git#1300]
Just updated Brackets to 1.7, the extension appears in the side menu but doesn't open the panel.
EDIT: I run Brackets on Ubuntu 15.10 64bit

**Comment by Malek-B** [comment]
+1

**Comment by xfg** [comment]
+1

**Comment by rabchev** [comment]
+1

**Comment by kowsoleea** [comment]
+1

**Comment by zaggino** [comment]
Guys, can you provide any errors or you'll just keep pushing +1s ?
I'm on vacation, though I've updated my Brackets to 1.7 today and I don't see anything wrong with it.

**Comment by Arxi** [comment]
After updating to 1.7 the click on Brackets-Git icon in the right sidepanel does nothing, the new/modified/deleted lines are not colored or shown at all, no branch shown near project, etc - in short, the extension does not work at all.

Is there any way we can provide some kind of error logs or further information to help?

**Comment by ex1st** [comment]
Developer tools of the Brackets print in console error after click to git-icon in sidebar:

> Uncaught TypeError: Cannot read property 'left' of undefined main.js:51
>     checkcursor main.js:51
>     (anonymous function) main.js:58
>     n.event.dispatch thirdparty.min.js:20
>     r.handle thirdparty.min.js:20

**Comment by Davinais** [comment]
I run Brackets on Mint 17 64bit.
Although the icon is shown, it doesn't work.
The branch icon on the left panel is also disappeared, only Git settings is working.

**Comment by kowsoleea** [comment]
The 1.7 linux 64 build has been updated. It seems to work fine now. The problem apparently was in Brackets, not in this extension. (also using Mint 17.3 64bit) (see Issue #468 from this repo and Issue #12525 from Brackets repo)

**Comment by oskarnrk** [comment]
I just downloaded the new 1.7 Linux 64bit version and all is working. So I close the issue. Thank you @zaggino for your time (and thanks for your extension!)
