### ISSUE TITLE
Make path to git executable configurable

### ISSUE THREAD

**Issue by rovf** [zaggino/brackets-git#1304]
Git is not necessarily in the PATH when Brackets is started. For example, I use Brackets for Windows and the Cygwin version of Git, and to not have my Windows tools interfer with the Git commands, I have the Cygwin bin directory (which contains git.exe) only in the PATH when running one of the Cygwin shells.

I suggest that you add a configuration parameter to brackets-git, which allows to specify the directory, where git can be found.

**Comment by zaggino** [comment]
That's already configurable in File -> Git Settings... -> Git configuration tab

**Comment by rovf** [comment]
Thank you! I didn't notice the "Git Settings" menu under "File".
