### ISSUE TITLE
Memory Leak

### ISSUE THREAD

**Issue by iegik** [zaggino/brackets-git#1315]
![2016-09-09 10 45 01](https://cloud.githubusercontent.com/assets/175293/18379591/060a4890-767c-11e6-8a2e-0ef761e6075a.png)

**Comment by zaggino** [comment]
This is a brackets core issue, already reported as https://github.com/adobe/brackets/issues/12765

**Comment by zaggino** [comment]
Fixed in brackets master by https://github.com/adobe/brackets/pull/12767
Will be fixed in brackets-electron 1.8.3 by https://github.com/zaggino/brackets-electron/pull/69
