### ISSUE TITLE
The extension doesn't work in the latest version fo Brackets, 1.8 

### ISSUE THREAD

**Issue by profstein** [zaggino/brackets-git#1323]
I get the following error:
![screen shot 2016-11-10 at 2 43 03 pm](https://cloud.githubusercontent.com/assets/6502138/20191591/2ed2d25c-a754-11e6-96a1-78ac1b3117e5.png)

I tried uninstalling and reinstalling and got the same error.

**Comment by zaggino** [comment]
Try restarting brackets after installing.
What's the error in error console? (F12)

**Comment by Cactusx09** [comment]
![image](https://cloud.githubusercontent.com/assets/9021479/20209001/6f50bae6-a7fa-11e6-89db-1c114643dfcf.png)

https://github.com/adobe/brackets/issues/12897

**Comment by Cactusx09** [comment]
Fix this after reinstall brackets and brackets-git

**Comment by AgamlaRage** [comment]
Same issue. **Win10** **Brackets1.8**
I can't uninstall it neither.

![brakets-git](https://cloud.githubusercontent.com/assets/15155827/20245787/87ecb442-a9a8-11e6-8c46-5ec4dacef0ef.png)

I tried to delete the extension manually in `C:\Users\YOURNAME\AppData\Roaming\Brackets\extensions\user`
But after, reinstall, I had the same issue.


Note:
I guess you're working more on Brackets-Electron now, and not on this king of compatibility problems... :(
With Brackets-Electron, you are making a EXELLENT job, it is way more FASTER on windows than the normal Brackets (at least, 2 times less to open or switch file) this is so great.
I hope normal Brackets will follow your updates more closer !
Just wanted to say !

**Comment by zaggino** [comment]
@profstein @Cactusx09 @AgamlaRage This is not a problem of Brackets-Git, but of Brackets itself when upgrading. Multiple people reported that clearing cache folder helps to get it running. Try deleting these:
![image](https://cloud.githubusercontent.com/assets/1067319/20248709/c158a4c6-aa3d-11e6-82ef-4f7c3c6fce07.png)

**Comment by AgamlaRage** [comment]
**I deleted the Brackets cache like you said**

This is insane, that **fix** my problem with **brackets-git** and my files are now loading as fast as in Brackets-Electron.

Thank you so much ! <3

**Comment by profstein** [comment]
Resetting the Cache didn't solve my problem.

When I looked at the developer tools I saw this error (Emmet was not loading either):
![screen shot 2016-11-15 at 1 01 20 am](https://cloud.githubusercontent.com/assets/6502138/20295844/80de673a-aad5-11e6-85a4-ff4497d30d03.png)

I had a couple of other errors there node related. So I tried to update node and found out that I didn't have XCode Command Line tools (MAC). I think that the latest MAC OS Upgrade changed something. So I Installed the command line tools again and then updated node. Then I opened Brackets and restarted with extensions and everything (Brackets Git and Emmet) seem to be working now. 

Not sure if it was the command line tools or node or both but it seems that my problem stems not from Brackets or the extension but from the OS upgrade which I just happened to do just before the Brackets upgrade.

**Comment by zaggino** [comment]
Thanks a lot @profstein , that might help some people!

**Comment by kvsrohit** [comment]
I am getting similar issue and noticed that thirdparty/urijs.browser.js and few other files are missing in the downloaded 'brackets-git-master.zip'.

[
![capture](https://cloud.githubusercontent.com/assets/20141873/20475895/22d25f92-aff4-11e6-87f1-cc1c60c63ba4.PNG)
](url)

**Comment by zaggino** [comment]
You can't just download zip file from github, that's not a valid installation procedure. Use extension registry.

**Comment by Dimonasdf** [comment]
I've unchecked "Remove BOM" option and checked "Add endline after eof", but Brackets still remove BOM and doesn't add line. What am I doing wrong?

![image](https://cloud.githubusercontent.com/assets/14166427/21753644/a784340c-d602-11e6-9f4a-69f2f1ca297b.png)

**Comment by zaggino** [comment]
@Dimonasdf can't replicate your problem and also that's another issue not related to above. Closing this thread.
