### ISSUE TITLE
My file is not uploaded to Github

### ISSUE THREAD

**Issue by luthfifr** [zaggino/brackets-git#1325]
Man, thanks for this great stuff, but it wouldn't be so great if my files couldn't be uploaded to Github. I init git in my working folder and then I hit Commit Button, after it finished I hit Push Button (of course I already add my github repo url as remote git), but when I check in my github repo, only 1 file is uploaded, the rest is not. I have more than 1400 files in that folder.

![screenshot at nov 16 17-24-27](https://cloud.githubusercontent.com/assets/22187764/20343615/a9c1195c-ac21-11e6-9a0e-dd4189cc86c3.png)

Would you give me a clue what did I miss or what did I do wrong?

Thanks

**Comment by zaggino** [comment]
When you're commiting, you need to check every file you want to commit. Or check all files.

**Comment by luthfifr** [comment]
I'm pretty sure that all files were checked. It solved now, I did a little mess using git command line, and finally it all can be pushed.
