### ISSUE TITLE
Extension Error

### ISSUE THREAD

**Issue by guiguitcho** [zaggino/brackets-git#1329]
Hello all
I work behind a proxy and I am not able to use the extension manager of Brackets so I manually installed brackets-git (as I did with the other extensions I am working with).
Unfortunately, when starting, it shows many errors in the developer tool: 
![image](https://cloud.githubusercontent.com/assets/25325841/22294059/26fb60a4-e312-11e6-97e2-3226d47284de.png)

Any help would be much appreciated !
Thanks a lot in advance

Guillaume

**Comment by zaggino** [comment]
Hi @guiguitcho , did you run `npm install` inside the extension directory after installing it manually?

**Comment by guiguitcho** [comment]
Thanks @zaggino for the tip. I then ran `npm install` but I got a bunch of error of this kind:
```
ERROR in ./~/moment/locale/af.js
Module not found: Error: a dependency to an entry point is not allowed
 @ ./~/moment/locale/af.js 7:50-70
```
Finally I still have errors concerning brackets-git when launching brackets:
Uncaught SyntaxError: Use of const in strict mode. /home/guillaume/.config/Brackets/extensions/user/brackets-git-master/dist/EventEmitter.js:3
Uncaught SyntaxError: Use of const in strict mode. /home/guillaume/.config/Brackets/extensions/user/brackets-git-master/dist/SettingsDialog.js:3
Uncaught SyntaxError: Use of const in strict mode. /home/guillaume/.config/Brackets/extensions/user/brackets-git-master/dist/Main.js:4
Uncaught SyntaxError: Use of const in strict mode. /home/guillaume/.config/Brackets/extensions/user/brackets-git-master/dist/Preferences.js:3

**Comment by zaggino** [comment]
Use branch 0.x that should be more stable https://github.com/zaggino/brackets-git/tree/0.x

**Comment by guiguitcho** [comment]
Indeed it works now ! Thanks !!
