### ISSUE TITLE
Ignores .gitignore

### ISSUE THREAD

**Issue by interactiveblueprints** [zaggino/brackets-git#30]
The .gitignore file in my repo containts (among others):
node_modules/
git status doesn't show the node_modules files but the plugin does.
Now I get a very long list with node_modules and the one file I actually changed.

**Comment by itjustwerks** [comment]
I'm also getting items from an ignored directory showing up in my list of changes. I have an auto-compiler installed for Coffeescript files, and when I change, for example, app.coffee as in the attached screenshot, "build/tmp/app.js" also shows up as modified. Notice that the directories ".sass-cache" and "build" are greyed/italicized in the file tree appropriately. I used the right-click "Add to .gitignore" option to add the directories to the ignore file. Help?

![gitignore issue](https://cloud.githubusercontent.com/assets/3847303/7049767/50f5540c-ddea-11e4-92dc-336d02a2374d.png)

**Comment by zaggino** [comment]
@itjustwerks 
1) don't ever dig out issues that have been closed for months/years please
2) if you go into command line and write `git status` do you also see this `build/tmp/app.js` entry?

Try using this from command line if that's the case:
```
git rm --cached build/tmp/app.js
git commit -m "i've deleted the build/tmp/app.js file from git"
```

**Comment by itjustwerks** [comment]
@zaggino, thanks for the pointer, I'm new to open-source stuff in general and Github specifically. I did as you mentioned and saw all of my build/tmp files, removed them, and everything looks clean now. Thank you so much!
