### ISSUE TITLE
Show number of commits behind remote

### ISSUE THREAD

**Issue by Wikunia** [zaggino/brackets-git#604]
At first thanks for this extension. I like the number after commiting to see how many commits can be pushed. It would be great to have the same feature the other way around so see how many commits the current branch is behind the remote. So the user knows when he has to click that button to update the local version.

**Comment by mattbell87** [comment]
@zaggino Can I submit a pull request to the master branch if I develop this feature?

**Comment by zaggino** [comment]
@mattbell87 definitely yes

**Comment by mattbell87** [comment]
@zaggino Thanks. I now have something working. Should we be doing a ```git fetch --all``` then a ```git rev-list --count ...```? Or would a fetch be too heavy?

**Comment by zaggino** [comment]
@mattbell87 `--all` would be too heavy, fetch only currently selected repository ... that should be enough, right?

**Comment by FezVrasta** [comment]
I think it would be nice to have a more frequent update on the current branch, and a less frequent update for all the branches, showing the commits behind and ahead in the branches dropdown.
![image](https://cloud.githubusercontent.com/assets/5382443/12170596/027ff8be-b543-11e5-90e8-b7607c91c6f0.png)
