### ISSUE TITLE
.gitignore "negative" logic confuses brackets-git

### ISSUE THREAD

**Issue by xmnboy** [zaggino/brackets-git#687]
See this `.gitignore` file for reference:

```
# ignore Cordova/PhoneGap CLI directories 
# in essence, everything but .xdk file and www directory 
# modified to work with XDK release 1199, needs additions file 
/* 
!/www 
!/config.xml 
!/README.md 
!/LICENSE.md 
!/intelxdk.config.additions.xml 
!/*.xdk 
!/*.xdke
```
- The `/*` line causes _all_ files and directories to be ignored.
- The `!/www` line causes the `www` directory to then be _un-ignored_ (to be included back after being ignored by the `/*` directive).
- The various files that are listed as _un-ignored_ in this `.gitignore` show up correctly in the Brackets folder tree.
- But `brackets-git` is confused and displays the `www` directory in that weird shadow italic font that is very hard to read; indicating that this directory, and its contents, are not being tracked.
- `git` does all the right things, so the `.gitignore` file is working.

In essence, in this example `brackets-git` is doing the right thing for _un-ignored_ files but not for directories that are _un-ignored_, and any folders and files contained within those _un-ignored_ directories.

**Comment by xmnboy** [comment]
Finally (!) was able to test, our Brackets is up-to-date, along with the proper version of this wonderful git plugin, and the problem is resolved. Thank you, very much. :+1:

**Comment by zaggino** [comment]
Well, that took a while but I'm glad it all works for you ;-)
