### ISSUE TITLE
"Pull from remote" with "Use rebase" does not refresh "Working Files" that had local commit changes

### ISSUE THREAD

**Issue by jlubean** [zaggino/brackets-git#794]
When I use the git pull button and chose the "Use rebase", any files I have open ("Working Files") that have local commit changes but have new remote changes now show the remote changes from the pull but don't show the changes from the local commit merged in.  If I do a "Cmd-R" to refresh Brackets, then I see my changes in the open files.

---

_Brackets 1.0.0-15191 (mac), Git 2.0.1 & Brackets-Git 0.13.36_

**Comment by thubbard29** [comment]
I am getting this issue in version 0.16.2.  After a commit, if I pull with rebase the editor window is not updated with the rebased commit.

Clicking the "Refresh Panel" button does not fix it.
