### ISSUE TITLE
Add / Commit list problems

### ISSUE THREAD

**Issue by NexuS-Pt** [zaggino/brackets-git#869]
When I change a file, is not added to list to commit.
![screenshot from 2014-12-25 02 46 12](https://cloud.githubusercontent.com/assets/5593818/5551955/348dd35e-8be0-11e4-922d-07e926103151.png)

--------------------------------

*Brackets 1.1.0-15558 (linux), Git 1.9.1 & Brackets-Git 0.14.9*

**Comment by zaggino** [comment]
Can you provide some console logs about this? Turn on the debug mode in the settings and open console with F12.

**Comment by NexuS-Pt** [comment]
Hi, 
in last update, the problem was solved ;)
