### ISSUE TITLE
.git folder is visible in file panel

### ISSUE THREAD

**Issue by alvint** [zaggino/brackets-git#873]
As of the latest update, the ".git" folder is shown in the file panel.
--------------------------------

*Brackets 1.1.0-15558 (mac), Git 1.9.3 (Apple Git-50) & Brackets-Git 0.14.9*

**Comment by alvint** [comment]
Also, contents of the Git folder are included in project searches, etc. Attempting to remove the Git folder with the Exclude Folders plugin has no effect.

**Comment by zaggino** [comment]
This is being resolved here https://github.com/adobe/brackets/issues/10183
