### ISSUE TITLE
brackets-git causes brackets to lock up--please ignore "node_modules" (if present) by default

### ISSUE THREAD

**Issue by alvint** [zaggino/brackets-git#874]
1. Create a node project.
2. Add lots of node dependencies (25 or 30). There will be on average 10s of thousands of files in the `node_modules` folder.
3. Open the Git panel and click the "initialize" button. Brackets freezes and you have to kill the process. Attempting to restart Brackets causes it to immediately freeze again. The only way to recover is to kill Brackets, remove the `.git` folder and restart.

The lockup appears to be result of BG trying to list the 10s of thousands of files in the Git panel to be staged. It may (or may not) also have something to do with the filesystem module's inability to handle over 30000 files. In any case, the easiest way to avoid the issue is to ignore `node_modules` by default, and possibly implementing a hard cap on the number of files shown in the git panel.

Issue occurs on OS X 10.10.

**Comment by zaggino** [comment]
Good catch, this will be fixed for the next version.

**Comment by zaggino** [comment]
Brackets Git updated to version 0.14.10.

**Comment by alvint** [comment]
Yup!
