### ISSUE TITLE
Accurate date on file history

### ISSUE THREAD

**Issue by carstenroselundberg** [zaggino/brackets-git#875]
The human language "2 months ago" is nice but not useful when trying to debug an order of events/commits

--------------------------------

*Brackets 1.1.0-15558 (mac), Git 1.9.3 (Apple Git-50) & Brackets-Git 0.14.9*

**Comment by sbruchmann** [comment]
Hello @carstenroselundberg,

you can change the date formatting via settings. Open the Brackets-Git panel and click on the settings icon.

![screen shot 2015-01-04 at 06 02 57 pm](https://cloud.githubusercontent.com/assets/141435/5606718/ffcb62b2-943b-11e4-867e-12c4bbaede11.png)

**Comment by carstenroselundberg** [comment]
How come I didn't think of that ... (shameful)

Loving this extension more and more - has completely replaced my git client

**Comment by zaggino** [comment]
:+1:
