### ISSUE TITLE
Git not found on Yosemite

### ISSUE THREAD

**Issue by FezVrasta** [zaggino/brackets-git#877]
I've Git installed using brew, the path is:

`/usr/local/bin/git` and is available in PATH with the command `git`but Brackets Git can't find it

**Comment by zaggino** [comment]
What's the result of
```
/usr/local/bin/git --version
```
?

**Comment by FezVrasta** [comment]
`git version 2.2.1`

I've written the complete path in the extension config at it works, but it should work even without have to change the config...

**Comment by zaggino** [comment]
Without the debug logs, I've no idea.

**Comment by FezVrasta** [comment]
https://gist.github.com/FezVrasta/01b1489ac32a70243a8e

**Comment by FezVrasta** [comment]
not sure but looks like you look for git in two specific paths and ignore the fact that I'm telling to use just `git`

**Comment by zaggino** [comment]
Three defaults are:
```
git --version
/usr/local/git/bin/git --version
/usr/bin/git --version
```
which on your pc return
```
Error: spawn ENOENT
ProcessUtils can't resolve the path requested: /usr/local/git/bin/git
Error: spawn ENOENT
```
So it means just `git --version` doesn't work and `/usr/local/bin/git` is not one of the three defaults.

**Comment by FezVrasta** [comment]
But homebrew is probably one of the most common ways to install git on osx so probably you should add it to the paths.

And by the way if I specify to use the command git without any path it should work

**Comment by zaggino** [comment]
Well you're getting `Error: spawn ENOENT` for `git --version` so `git` may not be in the lookup path.

**Comment by FezVrasta** [comment]
Git can be called from anywhere correctly using terminal so I can't see reasons of why it doesn't work here

**Comment by zaggino** [comment]
Not sure but that's what it's in the logs, they don't lie. I'm not familiar with the Mac path resolving, maybe it does work a different way than on Windows, paths used by the terminal might be different from paths used by the OS.

**Comment by KevinBatdorf** [comment]
I receive this error after installing the add-on and every time I load Brackets:
![screen shot 2015-01-28 at 2 28 27 am](https://cloud.githubusercontent.com/assets/1478421/5925332/60476d28-a695-11e4-9831-53a6069e3bb9.png)

Here is where my git is:
![screen shot 2015-01-28 at 2 28 49 am](https://cloud.githubusercontent.com/assets/1478421/5925380/b7eedac0-a695-11e4-948a-5bc00cbce77a.png)

I didn't install git via homebrew

**Comment by zaggino** [comment]
Go to `File` > `Git Settings...` > tab `Git Configuration` > `Path to Git executable`
and set `/user/local/bin/git` there.

I'll put that into the Git search paths for the next version.

**Comment by KevinBatdorf** [comment]
Thanks, works like a charm!
