### ISSUE TITLE
Can't Commit

### ISSUE THREAD

**Issue by pmerrity** [zaggino/brackets-git#884]
Tried to commit a change and get ready to push, but noticed nothing was happening. Checked the console and got this:   
![screen shot 2015-01-16 at 11 01 47 am](https://cloud.githubusercontent.com/assets/8050810/5780326/473670b0-9d6f-11e4-9e30-206d65858d2f.png)

**Comment by pmerrity** [comment]
For the record, after committing and pushing through terminal it worked just fine. I'm just not sure what made it hang up.

**Comment by zaggino** [comment]
You'd need to debug the `handleGitCommit` function when you run into this issue again using Brackets console (F12): https://github.com/zaggino/brackets-git/blob/83e0139b2d06ba6dae0713e7bf12ca73487a8d85/src/Panel.js#L522-L570

**Comment by pmerrity** [comment]
Noted for the future. Since then I haven't run into any issues, but I'll do that first thing if it happens again!

**Comment by zaggino** [comment]
Closing this for now as I wasn't able to replicate this and this is not a frequent issue.
