### ISSUE TITLE
Cannot write commit message when no file is open

### ISSUE THREAD

**Issue by JonathanWolfe** [zaggino/brackets-git#891]
To reproduce:
1. Make change
2. Close all active files
3. Check changes and press `Commit` button
4. Try to type commit message
5. Observe that no letters will appear

Opening a file and then pressing commit allows writing of a commit message.

--------------------------------

*Brackets 1.1.0-15558 (mac), Git 1.9.3 (Apple Git-50) & Brackets-Git 0.14.9*

**Comment by zaggino** [comment]
I can't replicate this using 1.1 on Windows, anyone else having the same issue? Is it Mac specific?

**Comment by JonathanWolfe** [comment]
Sorry, this is a bug with Brackets itself since it happens across any text input (file rename, extension search, everything) while no file is open.
