### ISSUE TITLE
Git-Ftp: path to ftp.less file is wrong in main.js

### ISSUE THREAD

**Issue by janicmikes** [zaggino/brackets-git#899]
When the git-ftp feature is turned on, an error gets logged telling that the git.less file could not be found.

I created a Pull Request (#900) in which I corrected the ftp file structure.
(Moving the style files into styles/ftp folder and the template file into templates/ftp/)

Please correct me if I was seeing this wrong.

Best regards

**Comment by zaggino** [comment]
Fixed in #900
