### ISSUE TITLE
Authentication

### ISSUE THREAD

**Issue by alexgv99** [zaggino/brackets-git#904]
I can not fill in the user and password fields because they are read-only, in push dialog. Also, if I try to push it anyway, a timeout occurs.
--------------------------------

*Brackets 1.1.0-15558 (win), Git 1.9.4.msysgit.1 & Brackets-Git 0.14.9*

**Comment by zaggino** [comment]
@alexgv99 are you using `ssh` or `https` ? `ssh` doesn't support username and password

**Comment by alexgv99** [comment]
hm... I'm using ssh, actually... is there any workaround to that?

**Comment by zaggino** [comment]
I use http://gitcredentialstore.codeplex.com/ tool to store my passwords. After installing it on Windows, you just need to do first push from command line (to enter the username and password) and then you can push from Brackets-Git without password.

For more info see https://github.com/zaggino/brackets-git/blob/master/README.md

**Comment by alexgv99** [comment]
I installed gitcredentialstore, but it just works in http connections... I'm still uncovered using ssh... anyway, I appreciate you've tried to help me. I think I'll just use the plugin in my own repository and, when I need send remote commands, I can use the command line. Thank you zaggino.
