### ISSUE TITLE
extension appears to obfuscate errors with other plugins

### ISSUE THREAD

**Issue by alvint** [zaggino/brackets-git#906]
The code in `main.js` around line 90 seems to 'steal' errors from other plugins, making them appear like they originate from brackets-git.

This is not really the fault of brackets-git, but if you're wrapping errors it may be something you want to address to avoid confusion.

**Comment by alvint** [comment]
Here's an error that is caused by the "Extensions Toolbar Reposition" plugin *without* brackets-git loaded. The "main.js:49" being referred to is in the "Extensions Toolbar Reposition" plugin:

![screen shot 2015-02-06 at 1 15 43 pm](https://cloud.githubusercontent.com/assets/622202/6084844/9249dad0-ae02-11e4-9a2a-84761c3421b4.png)

**Comment by alvint** [comment]
Here's the same error after brackets-git is installed. The error appears to be caused by brackets-git:

![screen shot 2015-02-06 at 1 21 13 pm](https://cloud.githubusercontent.com/assets/622202/6084910/47a6fcbe-ae03-11e4-9b15-2afb06fe5c4c.png)

**Comment by alvint** [comment]
The above is mostly a result of bizarre behavior by "Extensions Toolbar Reposition". This is the first error without brackets-git installed again, but after a reload. Note that references to its own main.js have mysteriously vanished:

![screen shot 2015-02-06 at 1 28 41 pm](https://cloud.githubusercontent.com/assets/622202/6085080/acefd0e0-ae04-11e4-8a07-252066644e5b.png)

**Comment by zaggino** [comment]
Yes @alvint , I'll remove this from the next release.

**Comment by zaggino** [comment]
Brackets Git updated to version 0.14.10.
