### ISSUE TITLE
git settings dialog not working, staged files not showing

### ISSUE THREAD

**Issue by div-tag** [zaggino/brackets-git#911]
It used to be every now and then, but it slowly started doing this more and more, until now the extension only works during the same session I install it in.

**Here is the problem:**
The bottom panel will not show staged files, and the Git Settings dialog will not open. The toolbar icon will not show a dot above it (signifing staged files) either.
I can still see file and commit history, though.

The console says:
![screenshot](https://cloud.githubusercontent.com/assets/6227700/6122764/5e11e5b6-b0ad-11e4-8d68-4eb6e33e9bee.png)
The error does not make sense to me, because when I go into the chrome debugger, it shows that the command *is* being registered with all the correct arguments, unless for some reason the callback is missing.

I don't think output from debug mode is relevant for this, but I can include it if needed.

**My specs:**
* Linux Mint 17.1 Cinnamon
* Brackets 1.2 pre-release and 1.1 (They both have the same issue)
* Brackets Git 0.14.10 and 0.14.9 (They both have the same issue)

I don't know if it was with the upgrade to 0.14.9, or if the issue was present earlier. I unfortunately did not look at the version number when I first noticed it.

This seems similar to #869, except the latest update did not fix the issue in my case. I don't know if it is the same problem or not.

I have tried looking into the code myself, but I can't figure it out. I really like your extension, but I don't know enough of its internals yet. I would be glad to help any way I can.

**Comment by zaggino** [comment]
@div-tag What other extensions do you have installed? Can you confirm this happening with Brackets-Git as only custom extension?

**Comment by div-tag** [comment]
I temporarily removed all my plugins, and installed Brackets Git. I can not get it to stop working, so it must be another extension.

Here is a list of all the extensions that I have:
* [PHP-SIG] PHP SmartHints
* Beautify
* Brackets Bookmarks
* Brackets Git
* CSS Shapes Editor for Brackets
* HTMLHint
* Indent Guides
* Inline Regex Editor
* JSONLint Extension for Brackets
* LESSHints
* Markdown Preview
* MDN Doc
* Minifier
* More HTML5 Code Hints
* Nav Shortcuts
* PHPLint for Brackets
* Railroad diagram of regular expressions
* Reasonable Comments
* Smooth Scroll
* Strip trailing spaces
* Upper Titlebar

I will begin adding them one by one until I find the offending extension.

**Comment by div-tag** [comment]
I found it!

Somehow the Minifier extension is causing it, and I see that it has already been addressed as a problem with a thirdparty library that they use.

I have had Minifier installed for as long as I have been using brackets, so I guess I never thought about it causing the problem.
Sorry to waste your time with something already addressed.
