### ISSUE TITLE
SH files being saved with dos line endings

### ISSUE THREAD

**Issue by vesrah** [zaggino/brackets-git#912]
Brackets 1.1.0-15558 / OSX 10.10

Creating or editing a .sh file and trying to run it comes back with:
`/bin/bash^M: bad interpreter: No such file or directory`
If you open the file in vim, set the file format to unix, and save it then the script works fine.  Reopening the file in brackets and saving it will cause the issue to happen again.

**Comment by zaggino** [comment]
@vesrah You need to open a issue here: https://github.com/adobe/brackets/issues
This is a repository for Brackets-Git integration.
