### ISSUE TITLE
remember a file's previous "staged" status when opening the "commit" dialog

### ISSUE THREAD

**Issue by alvint** [zaggino/brackets-git#917]
To reproduce:
1. In BG settings, map the "commit current file"  option to a shortcut.
2. Make changes to a file under version control.
3. Bring up the "commit" dialog with the shortcut.
4! Cancel the dialog by pressing [ESCAPE] or the Cancel button. The file is still marked as "staged" in Git, and opening the main BG panel also shows it marked as staged.

This may seem a bit nit-picky at first, but it's easy to later inadvertently add this file as part of a commit that shouldn't include it, since you may not realize it's still staged.

I'm not sure what the best solution is--maybe remember the file's previous "staged" status when the dialog is opened, and if the dialog is cancelled revert back to that? But with the "commit all" dialog you'd have to remember the previous status for all modified files.

**Comment by jhugohr** [comment]
We are an enthusiastic team looking to contribute to Brackets and would like to offer our services on this issue.

We think picking up this issue makes sense. If an action is cancelled, objects should remain in their original state and in this case might lead to committing an unwanted file/change.

**Comment by zaggino** [comment]
Hi @jhugohr feel free to proceed. Happy to see someone working on PRs.

**Comment by nmorenor** [comment]
@jhugohr and myself were looking at the shortcut commit issue. What we found is that when a Commit Single File and Commit All shortcuts are invoked, they stage the changes as first action of the shortcut command. We’ve worked some changes to make these two shortcuts, “commit all” and “commit current”, to stage the files just after the user clicks OK on the dialog. With this if the user cancel the dialog the index is left in the same state before the user trigger the shortcut commands.

Here is our initial proposal to start a discussion about this PR

https://github.com/zaggino/brackets-git/compare/master...Genuitec:issue-917

As a side note we also noticed an issue that could be tracked separately, when you use the commit current file and you have other staged changes the current file and the already staged file will be on the commit, I will log an issue to track this down.

**Comment by zaggino** [comment]
Concept of the solution is not bad, just pay attention to the error handling please, when having promise inside of promise, always use a return (when possible) and catch errors at the lowest promise. That's really needed here to be sure that some errors are not swallowed by any promises. Also, don't use over-complex codes which are hard to read:
```
if (files !== undefined) {
+            if ($.isArray(files)) {
+                _.forEach(function (next) {
+                    args.push(next);
+                });
+            } else {
+                args.push(files);
+            }
+        }
```
Can be easily replaced with
```
args = args.concat(files);
```
`concat` will push every element of files into args if it's an array, or push files into args if it's not
https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Array/concat

**Comment by zaggino** [comment]
The fix for this now landed in `master` brach of this repository. If you want to help, please install the extension from GitHub url and test that it works as supposed and nothing was broken. Thanks

I'll release this into the extension registry with the next release in a couple of days if no bugs will be found.
