### ISSUE TITLE
(minor) - opening the "commit current file" and "commit all files" dialog with a shortcut shows an error in Brackets

### ISSUE THREAD

**Issue by alvint** [zaggino/brackets-git#918]
This error doesn't seem to affect the operation of anything, and the dialog displays and works properly.

![screen shot 2015-02-18 at 6 59 09 pm](https://cloud.githubusercontent.com/assets/622202/6259418/5a9ac728-b7a0-11e4-963a-485fa589a2bf.png)

**Comment by zaggino** [comment]
Should be fixed in version `0.14.15`, please provide feedback. Thanks

**Comment by alvint** [comment]
Yup!
