### ISSUE TITLE
terminal shortcut for mac

### ISSUE THREAD

**Issue by zaggino** [zaggino/brackets-git#919]
@macbookandrew see this commit: https://github.com/zaggino/brackets-git/commit/45fcdf9d2b34813fcad33ce5f72593a57f1347ca

+

I have iTerm installed, it properly opens when closed, but I'd need to fix this from you if possible:
1. close iTerm with cmd+Q
2. click Brackets Git terminal icon.
3. launches properly
4. close iTerm with red cross in top left corner (it will stay running in the background as hinter by docker)
5. click Brackets Git terminal icon.
6. error:
```
Error: Error: /Users/***/Library/Application Support/Brackets/extensions/user/zaggino.brackets-git/shell/terminal.osa:434:498: execution error: iTerm got an error: Can’t set current terminal to "Brackets-Git". (-10006): osascript "/Users/zaggino/Library/Application Support/Brackets/extensions/user/zaggino.brackets-git/shell/terminal.osa" "/Users/zaggino/Library/Application Support/Brackets/extensions/user/zaggino.brackets-git/"
```

**Comment by macbookandrew** [comment]
@zaggino When you get a chance, could you test this new script? It should fix the above issue as well as handling existing and new sessions much more cleanly.

**Comment by zaggino** [comment]
@macbookandrew There has been a change in the behaviour I've currently realized.
When I open an iTerm tab, and run a gulp task for watch or an application with nodemon (so the iTerm stays busy) I can't open another window with clicking the terminal icon again. I could do that before. Isn't there possible to add another check whether the tab is running some command currently or not?

**Comment by zaggino** [comment]
What's worse, iTerm doesn't have right click -> open new tab (at the same working directory) :angry:

**Comment by macbookandrew** [comment]
I’ll see what I can do…
