### ISSUE TITLE
Terminal doesn't open on Windows.

### ISSUE THREAD

**Issue by megheaiulian** [zaggino/brackets-git#920]
When I click the Terminal icon nothing happens. 
I opened the Developers Tools and this error is showing:
![image](http://i.imgur.com/yL97Ewv.png)

**Comment by zaggino** [comment]
Should be fixed in version `0.14.15`, please provide feedback. Thanks

**Comment by megheaiulian** [comment]
It is fixed in 0.14.15 
Thank you!
