### ISSUE TITLE
Opening the bash console fails

### ISSUE THREAD

**Issue by Querela** [zaggino/brackets-git#921]
Opening the bash console using the Icon in the git window fails with "TypeError: Cannot read property 'split' of null". Trying to Report the bug in the error window also fails with a HTTP 404 for this URL "https://github.com/zaggino/brackets-git/issues/new?title=undefined&body=%5BI'm%20supposed%20to%20describe%20steps%20to%20replicate%20my%20issue%20here%20and%20if%20I%20don't%20do%20that%2C%20I%20understand%20that%20my%20issue%20will%20be%20probably%20ignored.%5D%0A%0A--------------------------------%0A%0A*Brackets%201.1.0-15558%20(win)%2C%20Git%201.9.5.github.0%20%26%20Brackets-Git%200.14.15*%0A%0A%0A%0A%60%60%60%0ATypeError%3A%20Cannot%20read%20property%20'split'%20of%20null%0A%60%60%60%0A%0A%60%60%60%0ATypeError%3A%20Cannot%20read%20property%20'split'%20of%20null%0A%20%20%20%20at%20open%20(file%3A%2F%2F%2FC%3A%2FUsers%2FErik%2FAppData%2FRoaming%2FBrackets%2Fextensions%2Fuser%2Fzaggino.brackets-git%2Fsrc%2Futils%2FTerminal.js%3A56%3A26)%0A%20%20%20%20at%20file%3A%2F%2F%2FC%3A%2FUsers%2FErik%2FAppData%2FRoaming%2FBrackets%2Fextensions%2Fuser%2Fzaggino.brackets-git%2Fsrc%2Futils%2FTerminal.js%3A157%3A21%0A%20%20%20%20at%20tryCatch1%20(file%3A%2F%2F%2FC%3A%2FUsers%2FErik%2FAppData%2FRoaming%2FBrackets%2Fextensions%2Fuser%2Fzaggino.brackets-git%2Fthirdparty%2Fbluebird.js%3A4988%3A19)%0A%20%20%20%20at%20Promise%24_callHandler%20%5Bas%20_callHandler%5D%20(file%3A%2F%2F%2FC%3A%2FUsers%2FErik%2FAppData%2FRoaming%2FBrackets%2Fextensions%2Fuser%2Fzaggino.brackets-git%2Fthirdparty%2Fbluebird.js%3A2333%3A13)%0A%20%20%20%20at%20Promise%24_settlePromiseFromHandler%20%5Bas%20_settlePromiseFromHandler%5D%20(file%3A%2F%2F%2FC%3A%2FUsers%2FErik%2FAppData%2FRoaming%2FBrackets%2Fextensions%2Fuser%2Fzaggino.brackets-git%2Fthirdparty%2Fbluebird.js%3A2349%3A18)%0A%20%20%20%20at%20Promise%24_settlePromiseAt%20%5Bas%20_settlePromiseAt%5D%20(file%3A%2F%2F%2FC%3A%2FUsers%2FErik%2FAppData%2FRoaming%2FBrackets%2Fextensions%2Fuser%2Fzaggino.brackets-git%2Fthirdparty%2Fbluebird.js%3A2521%3A14)%0A%20%20%20%20at%20Promise%24_fulfillPromises%20%5Bas%20_fulfillPromises%5D%20(file%3A%2F%2F%2FC%3A%2FUsers%2FErik%2FAppData%2FRoaming%2FBrackets%2Fextensions%2Fuser%2Fzaggino.brackets-git%2Fthirdparty%2Fbluebird.js%3A2666%3A14)%0A%20%20%20%20at%20Async%24_consumeFunctionBuffer%20%5Bas%2" ...

--------------------------------

*Brackets 1.1.0-15558 (win), Git 1.9.5.github.0 & Brackets-Git 0.14.15*

**Comment by zaggino** [comment]
Fixed in master, can you test by installing the extension from this url?
```
https://github.com/zaggino/brackets-git
```
![image](https://cloud.githubusercontent.com/assets/1067319/6287576/b22e1126-b966-11e4-8a64-2d27ebfd6b4b.png)

**Comment by Querela** [comment]
hi, you're great (and really fast to reply) :-)
works perfectly (no error message, bash appears)

ps.: replaced my existing plugin (because it was the same Version?), git accout data was lost (no problem) but the other configurations stayed the same
