### ISSUE TITLE
gitignore file created after cache dump

### ISSUE THREAD

**Issue by cfristoe** [zaggino/brackets-git#923]
The git hub extension froze up so I followed the guidelines to clear the cache and reinstall, which worked. Brackets now works, however, when I open  iTerm or Terminal I'm getting the following message: 
 <pre><code>calebfristoe at Calebs-iMac in ~/Desktop on master* </pre></code>

When I <pre><code>$git branch -v</pre></code> I get the following message: 

 <pre><code>  list   4b10dd6 .gitignore created by brackets-git extension
* master 4b10dd6 .gitignore created by brackets-git extension</pre></code>

Not really sure how to remedy this. Any help would be great. Thanks.

**Comment by zaggino** [comment]
Can you run `git rev-parse --show-toplevel` ?

**Comment by cfristoe** [comment]
Yes, it gives me the following, and then sends me back onto the master branch: 

<pre><code>$ git rev-parse --show-toplevel
/Users/calebfristoe
calebfristoe at Calebs-iMac in ~ on master*</pre></code>

Thanks,

**Comment by zaggino** [comment]
Why do you have a .git repo in your home folder?

**Comment by cfristoe** [comment]
Good question. It wasn't there before I cleared the cache, per the Brackets instruction. I wasn't sure it I just deleted if that would cause other problems.

**Comment by cfristoe** [comment]
You're right. Not sure how it ended up in there, but I removed and things are fine. Thanks for your help.
