### ISSUE TITLE
Close Files Not Modified In Git

### ISSUE THREAD

**Issue by staticinteger** [zaggino/brackets-git#932]
The "Close Files Not Modified In Git" button gets covered by the "Configure Working Set" button when you do a vertical or horizontal split.

--------------------------------

*Brackets 1.1.0-15558 (win), Git 1.9.5.msysgit.0 & Brackets-Git 0.14.16*

**Comment by zaggino** [comment]
Brackets Git updated to version 0.14.17.

**Comment by staticinteger** [comment]
Wow you fixed that fast! Keep up the great work!

**Comment by zaggino** [comment]
Thanks, closing ;-)

**Comment by fizzvr** [comment]
:+1:
