### ISSUE TITLE
Brackets freezing within seconds of starting up

### ISSUE THREAD

**Issue by johnalxndr** [zaggino/brackets-git#941]
after some debugging of extensions brackets-git seems to be causing brackets to freeze within 5 seconds of starting up. I tried the steps mentioned in https://github.com/zaggino/brackets-git/issues/915 and it still froze and crashed within seconds of reinstalling. 

worked fine the past few days. 

macbook pro yosemite

**Comment by zaggino** [comment]
I don't remember doing any updates that should break the things, did you install any new extensions?

**Comment by johnalxndr** [comment]
I removed all other extensions, only installed git-brackets...it froze immediately, do you think it has something to do with the new brackets 1.2 update?

**Comment by zaggino** [comment]
I don't think so, I'm on mac yosemite too and have been working with 1.2 all day today. Maybe deleting state and config files from Brackets could help if there's something messed up there but I'm just guessing.

**Comment by johnalxndr** [comment]
Alright ill try that out, thanks for the help.

**Comment by zaggino** [comment]
For others, state and config files are located in this folder:
```
/Users/zaggino/Library/Application Support/Brackets
```
and are called `brackets.json` and `state.json`. Deleting them will reset all settings done to Brackets.

**Comment by johnalxndr** [comment]
that worked beautifully, thanks

**Comment by zaggino** [comment]
Ah, too bad you don't have the old files, would help figuring out what was wrong.
If this ever happens again, be sure to backup them before deleting and send them to me please!

**Comment by johnalxndr** [comment]
I grabbed them out of trash, how do you want them sent over?

**Comment by zaggino** [comment]
zaggino at gmail.com is fine, thanks

**Comment by ngduc** [comment]
"only installed git-brackets...it froze immediately"

First time user here. For me, after installing git-brackets, press Ctrl-Opt-G to open its panel, it will freeze Brackets. It still freezes even after relaunching Brackets. I had to delete json settings.

**Comment by joris-** [comment]
I have intalled git-brackets and froze on start.
