### ISSUE TITLE
Pushing to remote failed

### ISSUE THREAD

**Issue by gichuwil** [zaggino/brackets-git#942]
Trying to push my project to a branch, it gives an error. Using Brackets.

--------------------------------

*Brackets 1.1.0-15558 (win), Git 1.9.5.msysgit.0 & Brackets-Git 0.14.17*

**Pushing to remote failed**

```
Error: error: src refspec feb-branch does not match any.
error: failed to push some refs to 'https://********@github.com/******/*****Web.git'
```

```
call: git push --porcelain --progress --force ****** feb-branch
Error: error: src refspec feb-branch does not match any.
error: failed to push some refs to 'https://***********@github.com/*****/******-Web.git'
    at Object.exports.toError (file:///C:/Users/*****_000/AppData/Roaming/Brackets/extensions/user/zaggino.brackets-git/src/ErrorHandler.js:162:19)
    at NodeConnection.<anonymous> (file:///C:/Users/*****_000/AppData/Roaming/Brackets/extensions/user/zaggino.brackets-git/src/Cli.js:176:44)
    at j (file:///C:/Program%20Files%20(x86)/Brackets/www/thirdparty/thirdparty.min.js:559:26860)
    at Object.k.fireWith (file:///C:/Program%20Files%20(x86)/Brackets/www/thirdparty/thirdparty.min.js:559:27673)
    at NodeConnection._receive (/utils/NodeConnection.js:492:34)
```

**Comment by ballweg** [comment]
I am also seeing this. 
````
Error: Permission denied (publickey).
fatal: Could not read from remote repository.
````
I generated a new SSH key and can push via command line, but not sure how I could tell Brackets GIT extension to use this key.

**Comment by zaggino** [comment]
Do you need to use password with this key?

Brackets Git just executes `git push` commands in your command line / terminal. It doesn't have any Git libraries included.

**Comment by ballweg** [comment]
I didn't need the password. However after seeing your message I figured the discrepancy might be caused by ssh-agent running in the background of the terminal window I was using, allowing push to work there but not in Brackets (or anywhere else). I closed all sessions, re-added the key and Brackets plugin is happy again.

Thanks for the reply and the excellent work on the plugin!

**Comment by gichuwil** [comment]
Still not working. Trying to do what @ballweg did and see if it will resolve.

**Comment by gichuwil** [comment]
Got the problem.
Initialized the folder with bash and did a commit.
