### ISSUE TITLE
Live preview duplicates on Commit button click

### ISSUE THREAD

**Issue by T3charmy** [zaggino/brackets-git#957]
1. Edit current file being viewed in Live preview
2. Save change
3. Go to commit change to server
4. Live preview duplicates

Not exactly sure if this is a problem with brackets itself or brackets-git. But I'm able to reproduce with above method.

--------------------------------

*Brackets 1.2.0-15697 (win), Git 1.9.5.msysgit.0 & Brackets-Git 0.14.17*

**Comment by zaggino** [comment]
anything concerning live preview should be reported to `adobe/brackets` repo
