### ISSUE TITLE
Switch to remote created branch

### ISSUE THREAD

**Issue by lippoliv** [zaggino/brackets-git#963]
Switch to branch, created on remot GIT host (by GitHub / GitLab for example)... That just works with the CLI at the Moment :/

--------------------------------

*Brackets 1.1.0-0 (win), Git 1.9.5.msysgit.0 & Brackets-Git 0.14.16*

**Comment by lippoliv** [comment]
What I mean is, i had to open CLI then ```git fetch``` and then ```git checkout -b MYREMOTECREATEDBRANCH``` and then in XDK I could work on that branch.
After that I was able to Switch branches using the GUI Control, but previous I had to use the CLI.

**Comment by zaggino** [comment]
In the new branch dialog, there's refresh button which does `fetch` to all your remote repositories and then you simply chose your remote branch there.
