### ISSUE TITLE
Pushing to remote failed

### ISSUE THREAD

**Issue by msmux** [zaggino/brackets-git#967]
Using Brackets git plugin, have had problems with work proxies so could be that.

--------------------------------

*Brackets 1.2.0-15697 (mac), Git 1.9.5 (Apple Git-50.3) & Brackets-Git 0.14.9*

**Pushing to remote failed**

```
Error: cmd-spawn-timeout: /usr/bin/git push --porcelain --progress origin master
```

```
call: git push --porcelain --progress origin master
Error: cmd-spawn-timeout: /usr/bin/git push --porcelain --progress origin master
    at timeoutPromise (file:///Users/james.nash/Library/Application%20Support/Brackets/extensions/user/zaggino.brackets-git/src/Cli.js:212:27)
    at file:///Users/james.nash/Library/Application%20Support/Brackets/extensions/user/zaggino.brackets-git/src/Cli.js:255:33
```

**Comment by zaggino** [comment]
Plugin only executes commands on the command line, in this case `git push --porcelain --progress origin master`. Timeout usually occurs when git is waiting for some input from the user like username or password. Currently there's no way to support that in the plugin. See https://github.com/zaggino/brackets-git#features-and-limitations

**Comment by msmux** [comment]
Ok, thanks for the quick reply.
