### ISSUE TITLE
Pushing to heroku

### ISSUE THREAD

**Issue by tencet** [zaggino/brackets-git#968]
How can I push my changes to heroku?

--------------------------------

*Brackets 1.2.0-15697 (linux), Git 1.9.1 & Brackets-Git 0.14.17*

**Comment by zaggino** [comment]
How do you do that usually from command line?

**Comment by tencet** [comment]
heroku login ...
heroku push

**Comment by zaggino** [comment]
Ok, we'd need a special buttons to launch those commands, it's not supported yet.

**Comment by tencet** [comment]
I config Automatic deploys from GitHub
