### ISSUE TITLE
Toolbar spacing/sizing is off

### ISSUE THREAD

**Issue by revxx14** [zaggino/brackets-git#977]
![broken buttons](http://i.imgur.com/PRY0syQ.jpg)

The buttons in the update toolbar are spaced very oddly, looks like they're missing some padding. I may take care of this later today.

**Comment by cheesypoof** [comment]
I am not seeing this on my installation. Are you sure you don't have another extension modifying relevant styles? It sure looks that way to me... The buttons are not normally that wide and the text not normally that large.

Nevertheless, given the proximity to merging #960, do investigate that as a possible cause.

**Comment by zaggino** [comment]
I also don't see any visual issues like the ones you have, might be a conflict with another extension.

**Comment by revxx14** [comment]
Ah, my bad, you where right. It was Brackets FTP Sync messing stuff up. I also had a minor visual issue with that plugin that I actually submitted a pull request to fix, wonder if that was me specific too... Hmm.
