### ISSUE TITLE
Pushing to remote has timed out even though the push finished

### ISSUE THREAD

**Issue by kleinjoshuaa** [zaggino/brackets-git#980]
It seems that everytime I try to push my github commit that it says that pushing to remote fails. Even though it seems that the push was successful. It leaves my local repo clean and does in fact update the remote origin. Not sure what's causing it to say that the remote push failed. 

--------------------------------

*Brackets 1.2.0-15697 (linux), Git 1.9.1 & Brackets-Git 0.14.19*

**Pushing to remote failed**

```
Error: cmd-spawn-timeout: git push --porcelain --progress origin master
```

```
call: git push --porcelain --progress origin master
Error: cmd-spawn-timeout: git push --porcelain --progress origin master
    at timeoutPromise (file:///home/josh/.config/Brackets/extensions/user/zaggino.brackets-git/src/Cli.js:212:27)
    at file:///home/josh/.config/Brackets/extensions/user/zaggino.brackets-git/src/Cli.js:255:33
```

**Comment by zaggino** [comment]
Timeout happens when the git process doesn't exit in 30 seconds by default, but I've no idea why it'd leave hanging after the push has been done. Did you try upgrading the git? On Linux latest should be `2.3.4` according to http://git-scm.com/downloads

**Comment by kleinjoshuaa** [comment]
Thanks martin, that appeared to be the issue.

The latest version of Git for Ubuntu 14.04 in the stable branch is 1.9.

Once I updated the issue was resolved.

**Comment by zaggino** [comment]
:+1:
