### ISSUE TITLE
undefined

### ISSUE THREAD

**Issue by daothanh** [zaggino/brackets-git#981]
[I'm supposed to describe steps to replicate my issue here and if I don't do that, I understand that my issue will be probably ignored.]

--------------------------------
Some times Git does not work when start Bracket or reload project
*Brackets 1.2.0-15697 (linux), Git 1.9.1 & Brackets-Git 0.14.19*

```
Error: cmd-spawn-timeout: git rev-parse --show-toplevel
```

```
call: git rev-parse --show-toplevel
Error: cmd-spawn-timeout: git rev-parse --show-toplevel
    at timeoutPromise (file:///home/thanh/.config/Brackets/extensions/user/zaggino.brackets-git/src/Cli.js:212:27)
    at file:///home/thanh/.config/Brackets/extensions/user/zaggino.brackets-git/src/Cli.js:266:29
```

**Comment by zaggino** [comment]
not replicable
