### ISSUE TITLE
Undo (CMD+Z) doesn't work anymore

### ISSUE THREAD

**Issue by dangelion** [zaggino/brackets-git#986]
After installing Brackets-Git the undo in Brackets doesn't work anymore.
Replicate the issue: Make a change to a file, save it, and try to undo. It doesn't work to me.

--------------------------------

*Brackets 1.2.0-15697 (mac osx latest yosemite), Git 1.9.5 (Apple Git-50.3) & Brackets-Git 0.14.19*

**Comment by zaggino** [comment]
disable clear whitespace on file save in the options
https://github.com/zaggino/brackets-git/issues/958

**Comment by dangelion** [comment]
It works, thanks. Is it a bug?

**Comment by zaggino** [comment]
It's a bug that has to be fixed directly in Brackets, not here in this extension.
