### ISSUE TITLE
increaes the width of git commit dialog box

### ISSUE THREAD

**Issue by programming-kid** [zaggino/brackets-git#997]
How do i increase the width of ```git commit``` dialog box ,its very narrow , is it calculated based on window size ? or is it fixed  because even when in fullscreen window git commit dialog box is very narrow 

pls help
thanks

**Comment by zaggino** [comment]
Made slightly bigger in `0.14.24`, see https://github.com/zaggino/brackets-git/commit/7264314a3f26624dbf0e11a964741d19d5eee3dc if you want to make further local changes.

**Comment by programming-kid** [comment]
How do i make local changes ??

**Comment by zaggino** [comment]
Extensions in Brackets are installed into these dirs:
```
win: %HOMEPATH%\AppData\Roaming\Brackets\extensions\user
mac: ~/Library/Application\ Support/Brackets/extensions/user/
linux: ~/.config/Brackets/extensions/user
```
You can make changes to their code there.
