### ISSUE TITLE
Gutter Marks question

### ISSUE THREAD

**Issue by mfromin** [zaggino/brackets-git#998]
I like gutter marks but the bright green strip is rather jarring in my dark theme.  Is it possible to change that by changing one of the LESS or CSS files?  If you can point me in the right direction I am happy to play with the colors to find something that works with my theme.

**Comment by zaggino** [comment]
You're probably looking for this: https://github.com/zaggino/brackets-git/blob/master/styles/commit-diff.less#L101-L108

**Comment by mfromin** [comment]
Awesome!  Thanks for the pointer.  New to Brackets but very much like your plugin for interacting with Git.
